# -*- coding: utf-8 -*-
"""Untitled101.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EPv5pNwYCZ7OiMtG9epxzDIDOL24e07r
"""

print("Hello World")