# -*- coding: utf-8 -*-
"""Untitled102.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17UyzyH14wtmWZK18OvNZvMCerZ95iarI
"""

print("Shashini")